version: "2"

linters:
  default: standard
  enable:
    - asasalint
    - bidichk
    - asciicheck
    - bodyclose
    - containedctx
    - contextcheck
    - cyclop
    - decorder
    - dogsled
    - dupl
    - dupword
    - errname
    - errorlint
    - fatcontext
    - forcetypeassert
    - funcorder
    - funlen
    - gocritic
    - gocyclo
    - godot
    - godox
    - gosec
    - grouper
    - iface
    - importas
    - ineffassign
    - interfacebloat
    - intrange
    - loggercheck
    - mnd
    - nilerr
    - nilnil
    - noctx
    - perfsprint
    - prealloc
    - reassign
    - testifylint
    - unconvert
    - unparam
    - varnamelen
    - wastedassign

run:
  concurrency: 4
  timeout: 5m
  tests: false
